### ISSUE TITLE
Messages are not being replicated on to consumer topic

### ISSUE THREAD

**Issue by chinastockproducts** [opencore/mirrormaker_topic_rename#4]
[MirrorMakerHandler.zip](https://github.com/opencore/mirrormaker_topic_rename/files/2010070/MirrorMakerHandler.zip)
We are trying to use the same from Gwen Shapiras , but consumer topic is not receiving any messages on target side.
export CLASSPATH=/Users/sxe518/Documents/test/MirrorMakerHandler/target/TopicSwitchingHandler-1.0-SNAPSHOT.jar
bin/kafka-mirror-maker.sh --consumer.config config/consumer.properties --producer.config config/producer.properties --whitelist test_.* —message.handler com.shapira.examples.TopicSwitchingHandler --message.handler.args ‘test,test123’

**Comment by cricket007** [comment]
I see you already commented here, so I'll point out out your class name is incorrect if you're using this project

Needs to be 

`--message.handler com.opencore.RenameTopicHandler`

**Comment by connectfirms** [comment]
[mirrormaker_topic_rename.zip](https://github.com/opencore/mirrormaker_topic_rename/files/2024649/mirrormaker_topic_rename.zip)
bin/kafka-mirror-maker.sh --consumer.config config/consumer.properties --producer.config config/producer.properties --whitelist test_.* --message.handler com.opencore.RenameTopicHandler  --message.handler.args ‘test,test123’

This is the code and command i used

**Comment by cricket007** [comment]
If you're not able to to explain what `test_.*` means in relation to the topics you're trying to mirror, I might suggest setting your whitelist simply to `test`

**Comment by connectfirms** [comment]
there are 2 topics : 
producer topic name : topic
consumer topic name : topic123.
so we are trying to whitelist both using test_.*

**Comment by cricket007** [comment]
Okay... my point is that `test_.*` will never match test, test123, topic, or topic123...

Its a regular expression, and if you don't understand what that means, please try setting it simply like the following. (Remove the underscore) 

`bin/kafka-mirror-maker.sh --consumer.config config/consumer.properties --producer.config config/producer.properties --whitelist test.* --message.handler com.opencore.RenameTopicHandler --message.handler.args 'test,test123'`

**Comment by connectfirms** [comment]
ok i will try using it.

**Comment by soenkeliebau** [comment]
I'll assume this has been fixed and close it, feel free to reopen if the problem persists.
