### ISSUE TITLE
You don't copy message header

### ISSUE THREAD

**Issue by vasili439** [opencore/mirrormaker_topic_rename#5]
Just started using mirrormaker_topic_rename and our application immediately became dead. During investigation we've recognized that the message headers lost during replication.

**Comment by slavirok** [comment]
Hi @vasili439,
I fixed the header issue. You can find the fix here:
[(https://github.com/slavirok/mirrormaker-rename-topic-handler)]

**Comment by vasili439** [comment]
Hi @slavirok, I can confirm that everything is working. Thank you!

**Comment by soenkeliebau** [comment]
I've added copying of message headers to the code, thanks for pointing this out!
