### ISSUE TITLE
Need clarification on ExactMessageHandler.java 

### ISSUE THREAD

**Issue by arun-421** [opencore/mirrormaker_topic_rename#8]
Please include the commands or arguments needs to be included for this java class. Also please add some description about the class.

**Comment by arun-421** [comment]
Is it used to fetch message from certain timestamp? Please provide clarification.

**Comment by soenkeliebau** [comment]
Hi Arun, I've added some explanation to the readme. There is also a header comment in the file that tries to give some insight. 
I hope this helps?

**Comment by arun-421** [comment]
Hi Soenkeliebau, Thanks for the clarification. Do you have any concept in which Mirror-Maker is used to fetch messages from a given timestamp?
