### ISSUE TITLE
Mirror-Maker to fetch message from a given time stamp.

### ISSUE THREAD

**Issue by arun-421** [opencore/mirrormaker_topic_rename#9]
Hi Soenkeliebau, Do you have any concept in which Mirror-Maker is used to fetch messages from a given timestamp?

**Comment by soenkeliebau** [comment]
Hi @arun-421 that functionality is provided by underlying Kafka functions. Please check out the kafka-consumer-groups tool that allows resetting commited offsets to timestamps.

**Comment by arun-421** [comment]
Thank you @soenkeliebau
